### PR TITLE
chore(samplr): fix vet errors in tests

### PR DESCRIPTION
**Pull request by orthros**

### CODE REVIEW

**Comment by BrennaEpp** [comment]
I also get vet errors in `samplr/git-go/commit_test.go`

**Comment by orthros** [comment]
Can you post a log of the errors? They dont appear in the presubmit checks and I cannot replicate

**Comment by BrennaEpp** [comment]
> Can you post a log of the errors? They dont appear in the presubmit checks and I cannot replicate

```
commit_test.go samplr/git-go
TestsliceCommitIterForEachReturnsInProperOrder has malformed name: first letter after 'Test' must not be lowercase go-vet [31, 1]
TestsliceCommitIterNextReturnsInProperOrder has malformed name: first letter after 'Test' must not be lowercase  go-vet [53, 1]
TestsliceCommitIterForEachReturnsEarlyOnError has malformed name: first letter after 'Test' must not be lowercase  go-vet [77, 1]
TestsliceCommitIterForEachReturnsEarlyOnErrorSignal has malformed name: first letter after 'Test' must not be lowercase  go-vet [104, 1]
```

I don't get these errors when I run `go vet` but they appear in the "problems" tab in VS-code.

**Comment by orthros** [comment]
Ah okay I'll update regardless. Thanks!

**Pull request merged**
