### PR TITLE
feat(maintner): add filter support

### PR DESCRIPTION
**Pull request by orthros**
Adds proper filtering support based on the Common Expression Language
(https://github.com/google/cel-spec).

This provides the ability for users of the IssueService API to filter
the results of their queries based on the "filter" string in
ListIssuesRequest and ListRepositoriesRequest.

### CODE REVIEW

**Comment by alixhami** [comment]
I don't speak Go, so I can't tell, but will the API return empty or an error if no issues match the filter?

**Comment by orthros** [comment]
If there are no issues that match the given filter it will return {} .

If the filter is invalid (e.g. `foo == 'bar` notice the lack of a closing `'`) it will return an error.

**Comment by orthros** [comment]
Okay. Updating this thread with some offline conversations.

Using the Common Expression Language to filter Issues introduces HUGE latency. It adds an average of about 9 ms of latency per Issue, (which is not unreasonable given what it is doing), but it quickly adds up. 

For example: a repository with 5000 Issues will take 45 seconds just to filter the Issues.

Having arbitrary filter support is still a great goal, but might need to be implemented in a different way/different layer.

**Comment by jmdobry** [comment]
ack, let's add filter support a different way

**Pull request closed without merging**
